/* Generated from the XML, SISO-REF-010-v25, 2018-08-29 */
package edu.nps.moves.dis7.enumerations;

/* UID 2 */
public enum Acronyms
{
    AA ("Anti-Aircraft"),
    AAA ("Anti-Aircraft Artillery"),
    AABNCP ("Advanced Airborne Command Post"),
    AAC ("Anti-Aircraft Common"),
    AAG ("Air-to-Air-to-Ground"),
    AASM ("Armement Air-Sol Modulaire (air-to-ground modular weapon)"),
    AAV ("Amphibious Assault Vehicle"),
    AAWSM ("Advanced Anti-Tank Weapon System-Medium"),
    ABCCC ("Airborne Command, Control and Communications"),
    ABL ("Airborne Laser"),
    ABM ("Anti-Ballistic Missile"),
    ABMOC ("Air Battle Management Operations Center"),
    ABS ("Amphibious Bridging System"),
    ACAS ("Airborne Collision Avoidance System"),
    ACV ("Armored Command Vehicle"),
    AD ("Air Defense"),
    ADA ("Air Defense Artillery"),
    ADAM ("Area Denial Artillery/Anti-Personnel Munition"),
    ADATS ("Air Defense Anti-Tank System"),
    ADCAP ("Advanced Capability"),
    ADCP ("Air Defense Communications Platform"),
    ADPCM ("Adaptive Differential Pulse Code Modulation"),
    ADSM ("Air Defense Suppression Missile"),
    AE ("Ammunition Ship"),
    AEPDS ("Advanced Electronic Processing and Dissemination System"),
    AESOP ("Airborne Electro-Optical Special Operations Payload"),
    AEW ("Airborne Early Warning"),
    AEWC ("Airborne Early Warning & Control"),
    AFARV ("Armored, Forward-Area, Rearm Vehicle"),
    AFAS ("Advanced Field Artillery System"),
    AFF ("Aufklarungs-, Fuhrungs- und Feuerleitfahrzeug (reconnaissance, command and fire control vehicle)"),
    AFS ("Auxiliary Fleet Support"),
    AFSK ("Audio Frequency Shift Keying"),
    AFSOF ("Air Force Special Operations Forces"),
    AFV ("Amphibious Fighting Vehicle"),
    AG ("Auxiliary General"),
    AGB ("Icebreaker"),
    AGI ("Auxiliary General Intelligence"),
    AGS ("Advanced Gun System"),
    AGSS ("Auxiliary Submarine"),
    AHIP ("Army Helicopter Improvement Program"),
    AHM ("Anti-Helicopter Mine"),
    AII ("Active Interrogation Indicator"),
    AIS ("Automatic Identification System"),
    AIT ("Auxiliary Intelligence Trawler"),
    AK ("Cargo Ship"),
    AKL ("Cargo Ship, Light"),
    ALARM ("Air-Launched Anti-Radiation Missile (UK)"),
    ALCM ("Air Launched Cruise Missile"),
    ALERT ("Attack and Launch Early Reporting to Theater"),
    ALRS ("Avion Leger de Surveillance et de Reconnaissance (Light Surveillance and Reconnaissance Aircraft)"),
    ALSV ("Armored Logistics Support Vehicle"),
    AM ("Amplitude Modulation"),
    AMC ("Armored Mortar Carrier"),
    AMG ("Antenna Mast Group"),
    AMR ("Anti-Materiel Rifle"),
    AMRAAM ("Advanced Medium Range Air-to-Air Missile"),
    AMV ("Armored Maintenance Vehicle"),
    AO ("Auxiliary Oiler"),
    AOE ("Fast Combat Support Ship"),
    AOL ("Auxiliary Oiler, Light"),
    AOR ("Auxiliary Oiler, Replenishment"),
    AOT ("Auxiliary Oiler, Transport"),
    AOTL ("Auxiliary Oiler, Transport Light"),
    AP ("Armor Piercing or Transport"),
    APA ("Additional Passive Activity"),
    APC ("Armored Personnel Carrier"),
    APDS ("Armor-Piercing Discarding Sabot"),
    APERS ("Anti-Personnel"),
    APFSDST ("Armor Piercing Fin Stabilized Discarding Sabot with Tracer"),
    API ("Armor Piercing Incendiary"),
    APKWS ("Advanced Precision Kill Weapon System"),
    APOBS ("Anti-Personnel Obstacle Breaching System"),
    APV ("Armored Patrol Vehicle"),
    AR ("Repair ship"),
    ARH ("Armed Reconnaissance Helicopter"),
    ARL ("Airborne Reconnaissance Low"),
    ARM ("Anti-Radiation Missile"),
    ARMD ("Anti-Radiation Missile Decoy"),
    ARSOF ("Army Special Operation Forces"),
    ARTHUR ("Artillery Hunting Radar"),
    ARV ("Armored Recovery Vehicle"),
    ASCII ("American Standard Code for Information Interchange"),
    ASCM ("Anti-Ship Cruise Missile"),
    ASDS ("Advanced SEAL Delivery System"),
    ASM ("Air-to-Surface Missile or Anti-Ship Missile"),
    ASR ("Submarine Rescue Ship"),
    ASRAAM ("Advanced Short Range Air-to-Air Missile"),
    ASROC ("Anti-Submarine Rocket"),
    ASTROS ("Artillery Saturation Rocket System"),
    ASW ("Anti-Submarine Warfare"),
    AT ("Anti-Tank"),
    ATacMS ("Army Tactical Missile System"),
    ATBM ("Anti-Tactical Ballistic Missile"),
    ATF ("Allschutz-Transport-Fahrzeug (all-protected transport vehicle)"),
    ATFLIR ("Advanced Targeting Forward Looking Infrared"),
    ATG ("Anti-Tank Gun"),
    ATGM ("Anti-Tank Guided Missile"),
    ATGW ("Anti-Tank Guided Weapon"),
    ATIRCM ("Advanced Threat Infrared Countermeasures"),
    ATTC ("All Terrain Tracked Carrier"),
    ATTV ("All-Terrain Tow Vehicle"),
    ATV ("All-Terrain Vehicle"),
    AUV ("Autonomous Underwater Vehicle"),
    AVLB ("Armored Vehicle-Launched Bridge"),
    AVRE ("Armored Vehicle, Royal Engineers"),
    AW ("Water Tanker"),
    AWACS ("Airborne Warning and Control System"),
    AXT ("Training ship tender"),
    BAT ("Brilliant Anti-Tank"),
    BATS ("Ballistic Aerial Target System"),
    BB ("Base Bleed"),
    BCP ("Battery Command Post"),
    BD ("Base Detonation"),
    BDR ("Battle Damage Repair"),
    BFUF ("Batteriefuhrungsfahrzeug/Unterstutzungszelle Flugabwehr (battery management vehicle/air defense support)"),
    BG ("Battle Group"),
    BIDS ("Biological Integrated Detection System"),
    BN ("Battalion"),
    BTOC ("Battalion Tactical Operations Center"),
    BVRAAM ("Beyond Visual Range Air-to-Air Missile"),
    BZ ("Benactyzine, Chemical warfare incapacitating agent"),
    C2 ("Command and Control"),
    C2W ("Command and Control Warfare"),
    C3 ("Command, Control and Communication"),
    C3I ("Command, Control, Communications and Intelligence"),
    C4I ("Command, Control, Communications, Computers and Intelligence"),
    CAEW ("Compact Airborne Early Warning"),
    CALCM ("Conventional Air Launched Cruise Missile"),
    CAPTOR ("Encapsulated Torpedo"),
    CASW ("Close Area Suppression Weapon"),
    CAT ("Combined Arms Team"),
    CAV ("Composite Armored Vehicle"),
    CAWS ("Close Assault Weapon System"),
    CBPSS ("Chemically and Biologically Protected Shelter System"),
    CBT ("Common Bridge Transporter"),
    CBU ("Cluster Bomb Unit"),
    CCITT ("International Telegraph and Telephone Consultative Committee"),
    CCS ("Communications Control Set"),
    CCTT ("Close Combat Tactical Trainer"),
    CDS ("Container Delivery System"),
    CEI ("Coupled Extension Indicator"),
    CEM ("Combined Effects Munition"),
    CFV ("Cavalry Fighting Vehicle"),
    CGS ("Common Ground Station"),
    CIRCM ("Common Infrared Countermeasures"),
    CITV ("Commander's Independent Thermal Viewer"),
    CIWS ("Close-In Weapon System"),
    CLAWS ("Complementary Low Altitude Weapon System"),
    CLV ("Command and Liaison Vehicle"),
    CMWS ("Common Missile Warning System"),
    COD ("Carrier Onboard Delivery"),
    COIL ("Chemical Oxygen Iodine Laser"),
    COM ("Command and Control Vehicle"),
    CP ("Command Post"),
    CPN ("Command Post Node"),
    CPV ("Command Post Vehicle"),
    CRC ("Control and Reporting Center"),
    CRE ("Control and Reporting Element"),
    CRG ("Communcations Relay Group"),
    CROWS ("Common Remotely Operated Weapon Station"),
    CRP ("Control and Reporting Post"),
    CSAR ("Combat Search and Rescue"),
    CSP ("Common Sensor Payload"),
    CTA ("Cased Telescopic Ammunition"),
    CTIS ("Central Tire Inflation System"),
    CTOL ("Conventional Take-Off and Landing"),
    CUAS ("Counter Unmanned Aircraft System"),
    CUCV ("Commercial Utility Cargo Vehicle"),
    CV ("Aircraft Carrier"),
    CVCC ("Combat Vehicle Command and Control"),
    CVN ("Aircraft Carrier Nuclear-powered"),
    CVS ("Antisubmarine Aircraft Carrier"),
    CVSD ("Continuously Variable Slope Delta (modulation)"),
    CVSG ("Carrier Vessel Submarine Guided"),
    CVT ("Continuous Variable Time"),
    CW ("Continuous Wave"),
    CWAR ("Continuous Wave Acquisition Radar"),
    DAACM ("Direct Airfield Attack Combined Munition"),
    DAGR ("Direct Attack Guided Rocket"),
    DAP ("Direct Action Penetrator"),
    DC ("Detection Center"),
    DD ("Destroyer"),
    DDG ("Guided Missile Destroyer"),
    DE ("Directed Energy"),
    DED ("Diesel Engine Driven"),
    DEUCE ("Deployable Universal Combat Earthmover"),
    DF ("Direction Finder"),
    DIRCM ("Directional Infrared Countermeasures"),
    DIS ("Distributed Interactive Simulation"),
    DME ("Distance Measuring Equipment"),
    DMSP ("Defense Meteorological Satellite Program"),
    DP ("Dual-Purpose"),
    DPICM ("Dual-Purpose Improved Conventional Munition"),
    DRA ("Dead Reckoning Algorithm"),
    DRM ("Dead Reckoning Model"),
    DRS ("Data Relay Satellite"),
    DS ("Discarding Sabot"),
    DSB ("Double Sideband"),
    DSCS ("Defense Satellite Communication System"),
    DSP ("Defense Support Program"),
    DST ("Destructor"),
    DTI ("Detonation Type Indicator"),
    DTSS ("Digital Topographic Support System"),
    DU ("Depleted Uranium"),
    DWT ("Deadweight Tonnage"),
    EA ("Electronic Attack"),
    EAS ("Electronic Attack Systems"),
    EBR ("Engin Blinde de Reconnaissance (armored reconnaissance vehicle)"),
    ECM ("Electronic Countermeasures"),
    ECR ("Electronic Combat/Countermeasures & Reconnaissance"),
    ECS ("Engagement Control Station"),
    EFM ("Enhanced Fighter Maneuverability"),
    EFP ("Explosively Formed Penetrator"),
    EFVS ("Electronic Fighting Vehicle System"),
    EGBU ("Enhanced Guided Bomb Unit"),
    ELAV ("Engineer LAV"),
    ELINT ("Electronic Intelligence"),
    EMATT ("Expendable Mobile ASW Training Target"),
    EMT ("Emergency Medical Technician"),
    EOD ("Explosive Ordnance Disposal"),
    EOS ("Electro-Optical Sensor"),
    EPLRS ("Enhanced Position Location Reporting System"),
    EPP ("Electric Power Plant"),
    EPS ("External Personnel System"),
    ERAM ("Extended Range Anti-Armor Munition"),
    ERFB ("Extended Range Full Bore"),
    ERINT ("Extended Range Interceptor"),
    ERS ("European Remote sensing Satellite"),
    ESK ("Einsatzfahrzeug fur spezialisierte Krafte (light protected vehicle for specialised forces)"),
    ESS ("Extended Self-protection Suite"),
    ESSS ("External Stores Support System"),
    ETRAC ("Enhanced Tactical Radar Correlater"),
    ETSI ("European Telecommunications Standards Institute"),
    EW ("Electronic Warfare"),
    E2I ("Endo-Exoatmospheric Interceptor"),
    EXTRA ("Extended Range Artillery"),
    FAASV ("Field Artillery Ammunition Support Vehicle"),
    FAE ("Fuel-Air Explosive"),
    FAMV ("Forward Area Multi-purpose Vehicle"),
    FAPDS ("Frangible Armor Piercing Discarding Sabot"),
    FASCAM ("Family of Scatterable Mines"),
    FAV ("Fast Attack Vehicle"),
    FCEP ("Fast Landing Craft for Equipment and Personnel"),
    FCR ("Fire Control Radar"),
    FCS ("Future Combat Systems"),
    FCV ("Forward Command Vehicle"),
    FDC ("Fire Direction Center"),
    FF ("Frigate"),
    FFG ("Guided Missile Frigate"),
    FFL ("Light Frigate"),
    FFLG ("Guided Missile Light Frigate or Corvette"),
    FISTV ("Fire Support Team Vehicle"),
    FLIR ("Forward Looking Infrared"),
    FM ("Frequency Modulation"),
    FMTV ("Family of Medium Tactical Vehicles"),
    FOGM ("Fiber Optic Guided Missile"),
    FOMP ("Fiber Optic Mortar Projectile"),
    FOV ("Forward Observation Vehicle"),
    FRISC ("Fast Raiding Interception Special Forces Craft"),
    FRS ("Forward Repair System"),
    FRT ("Forward Repair Team"),
    FS ("Fin Stabilized or Corvette"),
    FSG ("Corvette Guided Missile"),
    FSK ("Frequency Shift Keying"),
    FTI ("Fire Type Indicator"),
    GVLLD ("Ground/Vehicular Laser Locator Designator"),
    GAM ("GPS-Aided Munition"),
    GB ("Sarin"),
    GBCSH ("Ground Based Common Sensor Heavy"),
    GBCSL ("Ground Based Common Sensor Light"),
    GBR ("Ground-Based Radar"),
    GBU ("Guided Bomb Unit"),
    GD ("Soman"),
    GDT ("Ground Data Terminal"),
    GLCM ("Ground Launched Cruise Missile"),
    GLHH ("Ground Launched Hellfire: Heavy"),
    GMG ("Grenade Machine Gun"),
    GMLRS ("Guided Multiple Launched Rocket System"),
    GMT ("Guided Missile Transporter"),
    GP ("General Purpose"),
    GPH ("Gallons Per Hour"),
    GPMP ("General Purpose Machine Gun"),
    GPS ("Global Positioning System; Gunner's Primary Sight"),
    GSM ("Global System for Mobile Communications or Ground Station Module"),
    GTI ("German Tank Improvement"),
    GTK ("Gepanzertes Transport Kraftfahrzeug (armoured transport vehicle)"),
    HAGA ("Heavily Armored Ground Ambulance"),
    HARM ("High-Speed Anti-Radiation Missile"),
    HC ("Hexachloroethane Zinc"),
    HCER ("High Capacity Extended Range"),
    HE ("High Explosive"),
    HEAT ("High Explosive Anti-Tank"),
    HEDP ("High Explosive Dual Purpose"),
    HEER ("High Explosive Extended Range"),
    HEI ("High Explosive-Incendiary"),
    HEMAT ("Heavy Expanded Mobility Ammunition Trailer"),
    HEMTT ("Heavy Expanded Mobility Tactical Truck"),
    HEP ("High Explosive Plastic"),
    HERA ("High Explosive Rocket Assisted"),
    HET ("Heavy Equipment Transporter"),
    HILHS ("Heavy Integrated Load Handling System"),
    HIMAD ("High-to-Medium Altitude Air Defense"),
    HL ("Mustard-Lewisite"),
    HMEE ("High Mobility Engineer Excavator"),
    HMG ("Heavy Machine Gun"),
    HMMWV ("High Mobility Multipurpose Wheeled Vehicle"),
    HMT ("High Mobility Transporter"),
    HOJ ("Home On Jam"),
    HOT ("High subsonic Optically Teleguided"),
    HPI ("High-Power Illuminator"),
    HPW ("High Power Microwave"),
    HQ ("Headquarters"),
    HSIC ("High Speed Infiltration Craft"),
    HST ("Hypersonic Transport"),
    HTARS ("HEMTT Tanker Aviation Refueling System"),
    HUMRAAM ("HMMWV-mounted Advanced Medium Range Air-to-Air Missile"),
    HVAP ("High Velocity Armor Piercing"),
    HVM ("High Velocity Missile"),
    IADS ("Integrated Air Defense System"),
    IAI ("Intercom Attached Indicator"),
    IAP ("Integrated Armor Protection"),
    IBS ("Integrated Broadcast Service"),
    ICC ("Information Coordination Central"),
    ICM ("Improved Conventional Munition"),
    IEEE ("Institute of Electrical and Electronic Engineers"),
    IFDL ("Intra Flight Data Link"),
    IFF ("Identification, Friend or Foe"),
    IFU ("Integrated Fire Unit"),
    IFV ("Infantry Fighting Vehicle"),
    ILS ("Instrumented Landing System"),
    INS ("Inertial Navigation system"),
    IO ("Information Operations"),
    IR ("Infrared"),
    ISB ("Independent Sideband"),
    ISC ("Infantry Section Carrier"),
    ISLS ("Interrogation Path Side Lobe Suppression"),
    ISM ("IFF Simulation Mode"),
    ISR ("Intelligence Surveillance and Reconnaissance"),
    IST ("Institute for Simulation and Training"),
    ITAS ("Improved Target Acquisition system"),
    ITOW ("Improved TOW"),
    ITV ("Improved TOW Vehicle"),
    JAGM ("Joint Air-to-Ground Missile"),
    JASSM ("Joint Air-to-Surface Standoff Missile"),
    JDAM ("Joint Direct Attack Munition"),
    JETDS ("Joint Electronics Type Designation System"),
    JIEO ("Joint Interoperability Engineering Organization"),
    JLENS ("Joint Land Attack Cruise Missile Defense Elevated Netted Sensor System"),
    JNN ("Joint Network Node"),
    JPALS ("Joint Precision Approach and Landing System"),
    JSF ("Joint Strike Fighter"),
    JSTARS ("Joint Surveillance & Target Attack Radar System"),
    JTAGS ("Joint Tactical Ground Station"),
    JTIDS ("Joint Tactical Information Distribution System"),
    KE ("Kinetic Energy"),
    LACM ("Land Attack Cruise Missile"),
    LAHAT ("Laser Homing Attack/Laser Homing Anti-Tank"),
    LANTIRN ("Low Altitude Navigation and Targeting Infrared for Night"),
    LAPESAD ("Low Altitude Parachute Extraction System/Air Drop"),
    LAPV ("Light Armoured Patrol Vehicle"),
    LARC5 ("Lighter Amphibious Resupply Cargo, 5 ton"),
    LASA ("Light Air Support Aircraft"),
    LASH ("Lighter Aboard Ship"),
    LAV ("Light Armored Vehicle"),
    LAW ("Light Anti-Tank Weapon"),
    LCAC ("Landing Craft Air Cusion"),
    LCDB ("Low Collateral Damage Bomb"),
    LCM ("Landing Craft, Mechanized/Medium"),
    LCMR ("Lightweight Counter Mortar Radar"),
    LCP ("Landing Craft Personnel"),
    LCPA ("Landing Craft Personnel Air-Cushioned"),
    LCPL ("Landing Craft Personnel, Large"),
    LCS ("Littoral Combat Ships"),
    LCT ("Landing Craft, Tank"),
    LCU ("Landing Craft, Utility"),
    LCV ("Lightweight Combat Vehicle"),
    LCVP ("Landing Craft Vehicle Personnel"),
    LES ("Lincoln Experimental Satellite"),
    LGB ("Laser-Guided Bomb"),
    LHS ("Load Handling System"),
    LL ("Luftlandetruppen (airborne forces)"),
    LLC ("LHD Landing Craft"),
    LLDR ("Lightweight Laser Designator Rangefinder"),
    LML ("Lightweight Multiple Launcher"),
    LMTV ("Light Medium Tactical Vehicle"),
    LNG ("Liquefied Natural Gas"),
    LOCAAS ("Low Cost Autonomous Attack System"),
    LOG ("Logistics"),
    LOS ("Line-of-Sight"),
    LOSAT ("Line-of-Sight Anti-Tank"),
    LPD ("Amphibious Transport Dock"),
    LPG ("Liquefied Petroleum Gas"),
    LPH ("Landing Platform Helicopter"),
    LRASM ("Long Range Anti-Ship Missile"),
    LRLAP ("Long Range Land Attack Projectile"),
    LRPV ("Long Range Patrol Vehicle"),
    LRRSC ("Long-Range Recovery and Support Craft"),
    LS ("Launcher Station"),
    LSB ("Lower Sideband"),
    LSL ("Landing Ship Logistics"),
    LSM ("Landing Ship Medium"),
    LST ("Landing Ship Tank"),
    LSV ("Light Strike Vehicle"),
    LSVW ("Light Support Vehicle Wheeled"),
    LTD ("Laser Target Designator"),
    LTS ("LANTIRN Targeting System"),
    LTV ("Light Tactical Vehicle"),
    LUH ("Light Utility Helicopter"),
    LVC ("Live Virtual Constructive"),
    LVCI ("LVC Indicator"),
    LVT ("Landing Vehicle, Tracked"),
    LVTC ("LVT, Command"),
    LVTE ("LVT, Engineer"),
    LVTH ("LVT, Howitzer"),
    LVTP ("LVT, Personnel"),
    LVTR ("LVT, Recovery"),
    LWB ("Long Wheelbase"),
    LWTH ("Light Weight Towed Howitzer"),
    MAD ("Magnetic Anomaly Detection"),
    MADL ("Multifunction Advanced Data Link"),
    MANPADS ("Man-Portable Air Defense System"),
    MANTIS ("Modular, Automatic and Network Capable Targeting and Interception System"),
    MATV ("MRAP All Terrain Vehicle"),
    MBT ("Main Battle Tank"),
    MC ("Mortar Carrier"),
    MCAP ("Mine-Clearing/Armor Protection"),
    MCE ("Modular Control Equipment"),
    MCM ("Mine Countermeasures"),
    MCS ("Mine Countermeasures Support Ship"),
    MCT ("Medium Combat Truck"),
    MCU ("Munition Control Unit"),
    MEADS ("Medium Extended Air Defense System"),
    MEDEVAC ("Medical evacuation"),
    MEWSS ("Mobile Electronic Warfare Support System"),
    MG ("Machine Gun"),
    MHC ("Material Handling Crane or Minehunter Coastal"),
    MHE ("Material Handling Equipment"),
    MICLIC ("Mine-Clearing Charge"),
    MIDS ("Multifunctional Information Distribution System"),
    MILSTD ("Military Standard"),
    MIST ("Modular Interoperable Surface Terminal"),
    MITT ("Mobile Integrated Tactical Terminal"),
    MLMS ("Multipurpose Lightweight Missile System"),
    MLRS ("Multiple Launch Rocket System"),
    MMA ("Multi-Mission Maritime Aircraft"),
    MMP ("Mobile Mooring Platform"),
    MMS ("Mast-Mounted Sight"),
    MOAB ("Massive Ordnance Air Blast"),
    MOB ("Man Over Board"),
    MOPMS ("Modular Pack Mine System"),
    MP ("Multi-Purpose"),
    MPIM ("Multipurpose Individual Munition"),
    MPS ("Maritime Prepositioning Ship"),
    MPSM ("Multi-Purpose Submunition"),
    MPTSD ("Multi-Purpose Traced with Self Destruct"),
    MRAP ("Mine Resistant Ambush Protected"),
    MRCA ("Multi-Role Combat Aircraft"),
    MRL ("Multiple Rocket Launcher"),
    MRM ("Mid-Range Munition"),
    MRT ("Multi Role Transport"),
    MRTT ("Multi Role Tanker Transport"),
    MSD ("Minesweeper Drone"),
    MSE ("Mobile Subscriber Equipment"),
    MSO ("Minesweeper Ocean"),
    MSRT ("Mobile Subscriber Radiotelephone Terminal"),
    MSS ("Mortar Stowage System"),
    MTADS ("Modernized-Target Acquisition Designation Sight"),
    MTS ("Multi-Spectral Targeting System"),
    MTV ("Medium Tactical Vehicle"),
    MTVR ("Medium Tactical Vehicle Replacement"),
    MULE ("Modular Universal Laser Equipment"),
    NASAMS ("Norwegian Advanced Surface to Air Missile System"),
    NASP ("National Aerospace Plane"),
    NATO ("North Atlantic Treaty Organization"),
    NBC ("Nuclear/Biological/Chemical"),
    NDB ("Non-Directional Beacon"),
    NEARTIP ("Near Term Improvement Program"),
    NFH ("NATO Frigate Helicopter"),
    NLOS ("Non Line of Sight"),
    NLOSLS ("Non Line of Sight Launch System"),
    NLS ("National Launch System"),
    NA ("Not Applicable"),
    NSW ("Naval Special Warfare"),
    NTH ("Naval Transport Helicopter"),
    OCC ("Operational Control Center"),
    OPV ("Observation Post Vehicle or Offshore Patrol Vessel"),
    PAR ("Pulse Acquisition Radar"),
    PC ("Coastal Patrol"),
    PCF ("Patrol Craft Fast"),
    PCFG ("Patrol Craft Fast Guided missile"),
    PCM ("Pulse Code Modulation"),
    PCP ("Platoon Command Post"),
    PCRS ("Personnel Cargo Restraint and Segregation"),
    PD ("Point Detonation"),
    PDM ("Pursuit Deterrent Munition"),
    PDU ("Protocol Data Unit"),
    PGDT ("Portable Ground Data Terminal"),
    PGSS ("Persistent Ground Surveillance System"),
    PIR ("Pressure Ignition Rocket"),
    PLFS ("Poids Lourds Force Speciale (Heavy Special Forces Vehicle)"),
    PLS ("Palletized Load System"),
    PLST ("Palletized Load System Trailer"),
    PM ("Phase Modulation"),
    PNVS ("Pilot Night Vision Sensor"),
    POET ("Primed Oscillator Expendable Transporter (US RF decoy)"),
    POL ("Petroleum, Oil and Lubricants"),
    PPSL ("Primary SATCOM Link"),
    PPV ("Protected Patrol Vehicle"),
    PRI ("Pulse Repetition Interval"),
    PTDS ("Persistent Threat Detection System"),
    PTG ("Patrol Torpedo Gunboat"),
    PTIR ("Precision Target Illumination Radar"),
    QRCR ("Quick Reaction Capability Radar"),
    RA ("Rocket Assisted"),
    RAAM ("Rifle-launcher Anti-Armor Munition"),
    RAG ("Ring Airfoil Grenade"),
    RAI ("Radio Attached Indicator"),
    RAM ("Rolling Airframe Missile"),
    RAMPV ("Rapid Multi-Purpose Vehicle"),
    RAP ("Rocket-Assisted Projectile"),
    RARDEN ("Royal Armament, Research and Development Establishment and Enfield"),
    RCL ("Recoilless"),
    RCMAT ("Radio Controlled Miniature Aerial Target"),
    RCS ("Remote Control Station"),
    RDFLT ("Rapid Deployment Force Light Tank"),
    RECCE ("Reconnaissance"),
    RF ("Radio Frequency"),
    RGM ("Revolver Gun Mount"),
    RHIB ("Rigid-Hulled Inflatable Boat"),
    RIB ("Rigid-Inflatable Boat"),
    RMP ("Reprogrammable Microprocessor (Stinger variant)"),
    RN ("Royal Navy"),
    RNXS ("Royal Naval Auxiliary Service"),
    ROR ("Range-Only-Radar"),
    ROV ("Remotely Operated Vehicle"),
    ROWPU ("Reverse Osmosis Water Purification Unit"),
    RSTA ("Reconnaissance, Surveillance and Target Acquisition"),
    RTCST ("Rough Terrain Container Straddle Truck"),
    RTTL ("Range Target Towing Launch"),
    SACLOS ("Semi-Automatic Command to Line of Sight"),
    SADARM ("Sense and Destroy Armor"),
    SADL ("Situation Awareness Data Link"),
    SAL ("Semi-Active Laser"),
    SAM ("Surface-to-Air Missile"),
    SAMOC ("Surface to Air Missile Operations Centre"),
    SAP ("Semi-Armor Piercing"),
    SAR ("Search and Rescue"),
    SATCOM ("Satellite Communications"),
    SAW ("Squad Automatic Weapon"),
    SCATMINE ("Scatterable Mines"),
    SD ("Self-Destruct"),
    SDI ("Strategic Defense Initiative"),
    SDS ("Satellite/Space Defense System"),
    SDV ("SEAL Delivery Vehicle"),
    SEAD ("Suppression of Enemy Air Defenses"),
    SEAL ("Sea, Air, Land"),
    SEE ("Small Emplacement Excavator"),
    SEMA ("Special Electronic Missions Aircraft"),
    SETSS ("Satellite Earth Terminal Subsystem"),
    SFW ("Sensor Fused Weapon"),
    SH ("Squash Head"),
    SHF ("Super High Frequency"),
    SHORAD ("Short Range Air Defense"),
    SIBRS ("Space-Based Infrared System"),
    SICPS ("Standard Integrated Command Post System"),
    SIGINT ("Signal Intelligence"),
    SIMNET ("Simulation Networking"),
    SINCGARS ("Single Channel Ground-Air Radio System"),
    SIR ("Search and Interrogation Radar"),
    SLAM ("Standoff Land Attack Missile"),
    SLAMRAAM ("Surfaced Launched Advanced Medium Range Air-to-Air Missile"),
    SLAP ("Saboted Light Armor Penetrator"),
    SLBM ("Submarine Launched Ballistic Missile"),
    SMARTT ("Secure Mobile Anti-Jam Reliable Tactical-Terminal"),
    SMAW ("Shoulder-launched Multipurpose Assault Weapon (US)"),
    SMFT ("Semi-Trailer Mounted Fabric Tank"),
    SNA ("Soviet Naval Air"),
    SNLE ("Sous-marin Nucleaire Lanceur d'Engin (device launching nuclear submarine)"),
    SNLENG ("Sous-marin Nucleaire Lanceur d'Engins de Nouvelle Generation (next generation device launching nuclear submarine)"),
    SOF ("Special Operations Forces"),
    SOW ("Stand-Off Weapon"),
    SP ("Self-Propelled"),
    SPAS ("Shuttle Pallet Satellite"),
    SRAM ("Short Range Attack Missile"),
    SRAW ("Short-Range Assault Weapon"),
    SRBM ("Short-Range Ballistic Missile"),
    SRTA ("Short Range Training Ammunition"),
    SS ("Submarine Attack"),
    SSA ("Submarine Auxiliary/Cargo Submarine"),
    SSAN ("Submarine Auxiliary/Cargo Submarine, Nuclear Power"),
    SSB ("Single Sideband or Submarine Ballistic Missile"),
    SSBN ("Submarine Ballistic Missile, Nuclear Powered"),
    SSC ("Coastal Submarine"),
    SSG ("Guided Missile Submarine"),
    SSGN ("Guided Missile Submarine, Nuclear-Powered"),
    SSK ("Hunter-Killer/ASW Submarine"),
    SSM ("Midget Submarine or Surface-to-Surface Missile"),
    SSN ("Attack Submarine, Nuclear-Powered"),
    SSNR ("Special Attack Submarine"),
    SSP ("Attack Submarine, Diesel Air-Independent Power"),
    SST ("Training Submarine"),
    STAFF ("Smart Target Activated Fire and Forget"),
    STARS ("Surveillance Target Attack Radar System"),
    START ("SHF Tri-Band Advanced Range Extension Tactical Terminal"),
    STEP ("Space Test Experiment Program"),
    STOVL ("Short Take-Off and Vertical Landing"),
    STSS ("Surface Terminal Subsystem"),
    SUBROC ("Submarine Rocket"),
    SUGV ("Small Unmanned Ground Vehicle"),
    SuR ("Surveillance Radar"),
    SURTASS ("Surveillance Towed Array Sonar System"),
    SUSV ("Small Unit Support Vehicle"),
    SUV ("Sports Utility Vehicle"),
    SWAARM ("Smart Weapon Anti-Armor"),
    SWAT ("Special Weapons And Tactics"),
    SWATH ("Small Water-plane Area Twin Hull"),
    T ("Tracer"),
    TAC ("Tactical"),
    TACAMO ("Take Charge and Move Out"),
    TACAN ("Tactical Air Navigation"),
    TACTOM ("Tactical Tomahawk"),
    TAD ("Trailing Arm Drive"),
    TADS ("Target Acquisition Designation Sight"),
    TAOC ("Tactical Air Operation Center"),
    TARG ("Telescoped Ammunition Revolver Gun"),
    TASM ("Tomahawk Anti-Ship Missile"),
    TBM ("Tactical Ballistic Missile"),
    TCAS ("Traffic Alert and Collision Avoidance System"),
    TCD ("Landing Ship, Dock"),
    TCDL ("Tactical Common Data Link"),
    TDL ("Tactical Data Link"),
    TDRSS ("Tactical Data Relay Satellite System"),
    TEI ("Transferred Entity Indicator"),
    TEL ("Transporter Erector Launcher"),
    TELAR ("Transporter Erector Launcher and Radar"),
    TES ("Tactical Exploitation System"),
    TGW ("Terminally Guided Weapon"),
    THAAD ("Theater High-Altitude Area Defense"),
    TIR ("Tracking and Illumination Radar"),
    TLAM ("Tomahawk Land Attack Missile"),
    TLB ("Trailer Launched Bridge"),
    TMD ("TAC Munition Dispenser"),
    TNFH ("Transport NFH"),
    TOW ("Tube-launched, Optically-tracked, Wire-guided"),
    TPC ("Tactical Psychological Operations Company"),
    TPCSDST ("Target Practice Cone Stabilized Discarding Sabot Tracer"),
    TTH ("Tactical Transport Helicopter"),
    TUA ("TOW Under Armour"),
    TUAV ("Tactical UAV"),
    TUGS ("Tactical Unattended Ground Sensor"),
    TUTT ("Twin Unit Tractor Tugs"),
    US ("United States"),
    UAV ("Unmanned Aerial Vehicle"),
    UCAS ("Unmanned Combat Air Systems"),
    UCAV ("Unmanned Combat Aerial Vehicle"),
    UGS ("Unattended Ground Sensor"),
    UGV ("Unmanned Ground Vehicle"),
    UID ("Unique Identifier"),
    UK ("United Kingdom"),
    UPIN ("User Protocol Identification Number"),
    UR ("Upper Receiver"),
    USB ("Upper Sideband"),
    USV ("Unmanned Surface Vehicle"),
    UUGS ("Urban Unattended Ground Sensor"),
    UUV ("Unmanned Underwater Vehicle"),
    VBL ("Vehicule Blinde Leger (light armoured vehicle)"),
    VBR ("Vehicule Blinde a Roues (wheeled armoured vehicle)"),
    VCI ("Vehicule de Combat d'Infanterie"),
    VEMASID ("Vehicle Magnetic Signature Duplicator"),
    VIP ("Very Important Person"),
    VLAP ("Velocity Enhanced Artillery Projectile"),
    VLF ("Very Low Frequency"),
    VLFS ("Vehicule Leger Forces Speciales (Light Special Forces Vehicle)"),
    VLSMS ("Vehicle Launched Scatterable Mine System"),
    VOR ("Variable Omni-Ranging"),
    VORTAC ("Combined VOR and TACAN"),
    VRRTFLT ("Variable Reach Rough Terrain Forklift Truck"),
    VSB ("Vestigial Sideband"),
    VSHORAD ("Very Short Range Air Defense"),
    VT ("Variable Time"),
    VX ("Venomous agent X"),
    WAAM ("Wide Area Anti-Armor Munition"),
    WAM ("Wide Area Mine"),
    WCMD ("Wind-Corrected Munitions Dispenser"),
    WFU ("Weapon Fire Unit"),
    WP ("White Phosphorus"),
    WPS ("West Philippine Sea"),
    XLWB ("Extra Long Wheelbase"),
    YDG ("Degaussing tender");

    private final String description;

    Acronyms(String description)
    {
        this.description = description;
    }

    public String getDescription()
    {
        return description;
    }
    
    @Override
    public String toString()
    {
        return "Acronyms: " + name();
    }
}
